name: totes-pipline

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout and clone repo
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ' 3.12.6'
      - name: install requirements
        run: make requirements
      - name: dev setup
        run: make dev-setup
      - name: run-all-checks
        run: make run-checks
        env:
          PG_USER: ${{ secrets.PG_USER }}    
          PG_PORT: ${{ secrets.PG_PORT }}    
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}    
          PG_HOST: ${{ secrets.PG_HOST }}    
          PG_DATABASE: ${{ secrets.PG_DATABASE }}         

  deploy-lambda:
    name: deploy-lambda
    needs: run-tests
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      - name: terraform init
        working-directory: terraform
        run: terraform init
      - name: terraform plan
        working-directory: terraform
        run: terraform plan
      - name: terraform format
        working-directory: terraform
        run: terraform fmt